### ISSUE TITLE
Problem with the firmware

### ISSUE THREAD

**Issue by EgorMuhin** [AchimPieters/ESP8266-HomeKit-Blinds#2]
Good afternoon, I wanted to try your project, but I can't flash the esp, wifi does not start. Could you check it out or is there any additional instruction for your project? Or when can I expect new software? page "For More Information Visit https://www.studiopieters.nl/esp8266-homekit-blinds" it doesn't work the same way.
Do I need blankconfig and rboot for the firmware? if so, where can I get it?
Thank you in advance for your response and for your invaluable projects.

**Comment by AchimPieters** [comment]
@EgorMuhin here you will find all information needed": https://www.studiopieters.nl/homekit-accessoires/
