### ISSUE TITLE
Esp32

### ISSUE THREAD

**Issue by exrector** [AchimPieters/ESP8266-HomeKit-Blinds#4]
could you transfer the project to esp32 + step motor 28byj-48 + driver uln2003 board.  I tried to do it myself, but I have endless problems.  I didn’t wait for help in the respective development branches: Maxim Kulkin and espresiff 😭

**Comment by exrector** [comment]
Please 🙏🏻.  I've been trying to make blinds for one year.

**Comment by kunwarsethi** [comment]
> Please 🙏🏻. I've been trying to make blinds for one year.

Follow Homekidd's guide, they use a ULN2003 board on that tutorial https://github.com/HomeKidd/ESP8266-Homekit-Smart-Blinds

**Comment by exrector** [comment]
> > Пожалуйста 🙏🏻. Я пытался сделать жалюзи в течение одного года.
> 
> Следуйте руководству Homekidd, в этом руководстве они используют плату ULN2003 [https://github.com/HomeKidd/ESP8266-Homekit-Smart-Blinds .](https://github.com/HomeKidd/ESP8266-Homekit-Smart-Blinds)

This project is also non-customizable and closed.  useless

**Comment by AchimPieters** [comment]
@exrector This is a repro build on a ESP8266. You can build everything you want yourself start here: https://www.studiopieters.nl/homekit-accessoires/
